name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker
      - name: Set up Docker Compose
        run: |
          docker-compose up -d --build

      # Wait for services to be ready
      - name: Wait for MySQL to be ready
        run: |
          until docker exec mysql mysqladmin ping -h"127.0.0.1" --silent; do
            echo "Waiting for MySQL...";
            sleep 1;
          done

      # Run Laravel tests
      - name: Run Laravel tests
        run: |
          docker exec laravel.test php artisan test

      # Run React tests
      - name: Run React tests
        run: |
          docker exec <react-container-name> npm test --prefix frontend

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_USER }}
          key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
          script: |
            cd /path/to/your/project
            docker-compose down
            docker-compose up -d --build
