name: CI/CD Pipeline Test

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        ports:
          - 3306:3306

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

<<<<<<< HEAD
      # Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      # Build and Start Docker Compose
      - name: Set up Docker Compose
=======
      # Set up Docker
      - name: Build and Start Docker Compose
>>>>>>> 85928bbc05f759bfcbdbd1a1959b2ee4fc038d45
        run: |
          docker-compose up -d

      # Wait for MySQL to be ready
      - name: Wait for MySQL to be ready
        run: |
          until docker exec mysql mysqladmin ping --silent; do
            echo "Waiting for MySQL...";
            sleep 1;
          done

      # Run Laravel Tests
      - name: Run Laravel Tests
        run: |
          docker exec laravel.test php artisan test

      # Run React Tests
      - name: Run React Tests
        run: |
          docker exec laravel.test npm test --prefix frontend
